/* type.h */


typedef  char              Bool;         /* type booleen */
typedef  unsigned char     uchar;
typedef  unsigned short    ushort;
typedef  unsigned long     ulong;
typedef  long              phys_bytes;   /* mem.h   */
typedef  unsigned          phys_click;   /* mem.h   */
typedef  int               MARKER[1];    /* shell.h */
typedef  unsigned          portaddr;     /* slu.h   */
typedef  unsigned          DBADDR;       /* disk.h  */
typedef  int               SEM;


#include "ftype.h"
