/* declaration des messages de nmx_comp et nmx_make */

/* commun */

extern char checkString[];
extern char compString[];
extern char assString[];
extern char linkString[];
extern char nCfileStr[];
extern char nAfileStr[];


extern char compStr[];
extern char assStr[];
extern char mkeStr[];
extern char linkStr[];

extern char doCompStr[];
extern char doAssStr[];

extern char errmalloc[];
extern char errStr[];
extern char succStr[];
extern char noCompStr[];
extern char noAssStr[];
extern char checkDepStr[];
extern char tempStr[];
extern char mmodStr[];

/* nmx_make */
extern char noPrjStr[];
extern char noPrjFileStr[];
extern char syntErr1[];
extern char syntErr2[];
extern char syntErr3[];
extern char chkStr[];
extern char fileNfStr[];
extern char fileNsrcStr[];
extern char macNfStr[];
extern char fileUpDStr[];
extern char undefMacStr[];
extern char redefMacStr[];
extern char tooMaMacStr[];
extern char cannotCrMac[];
extern char breakMake[];
extern char noUsrStr[];
extern char multitaskStr[];

/* nmx_link */
extern char doLinkStr[];
extern char noLinkStr[];
extern char notFoundStr[];

/* mkd_ref */
extern char DbaseUpd[];
extern char breakRef[];
extern char dbaseStr[];
extern char refStr[];
extern char lnkDBstr[];
extern char mkeDBstr[];
extern char recDBfiles[];
extern char scanStr[];
extern char bldStr[];
extern char dbStr[];
extern char outofmem[];
extern char dbaseErrStr[];
extern char dbaseFerrStr[];
extern char dbaseOpenErr[];
extern char dbaseIntegrityErr[];
extern char generateStr[];
extern char dbaseLnkStr[];
extern char nDefStr[];
extern char nExtStr[];
extern char dbaseFunc[];
extern char creaDBstr[];

/* REFCALL */
extern char refCallOpenf[];
extern char refCallIncorr[];
extern char refCallwkf[];
extern char refCallOver[];